### ISSUE TITLE
Failing to run tests

### ISSUE THREAD

**Issue by luontola** [jlangr/pubmob#1]
`npm run test` fails with the following error.  I'm using node v13.12.0 on macOS.

```
    /Users/esko/devel/pubmob/src/name-normalizer.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { normalize } from './name-normalizer';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
```

**Comment by jlangr** [comment]
Initial push was missing the .babelrc file. Please pull & try again (works ok for me now).

**Comment by luontola** [comment]
Please still push the commit

**Comment by luontola** [comment]
Works now. 👍
